language: minimal

services:
  - docker

env:
  - RELEASEVER=1.0
  - RELEASEVER=2.0
  - RELEASEVER=3.0

script:
  - docker run -e RELEASEVER=${RELEASEVER} --rm -it -v$(pwd):/check -w/check photon:${RELEASEVER} ./ci/repo_check.sh
